INSERT INTO competition VALUES(2014, 'San Antonio Spurs');
INSERT INTO competition VALUES(2013, 'Miami Heat');
INSERT INTO competition VALUES(2012, 'Miami Heat');
INSERT INTO competition VALUES(2011, 'Dallas Mavericks');
INSERT INTO competition VALUES(2010, 'Los Angeles Lakers');
INSERT INTO competition VALUES(2009, 'Los Angeles Lakers');
INSERT INTO competition VALUES(2008, 'Boston Celtics');
INSERT INTO competition VALUES(2007, 'San Antonio Spurs');
INSERT INTO competition VALUES(2006, 'Miami Heat');
INSERT INTO competition VALUES(2005, 'San Antonio Spurs');


INSERT INTO competition VALUES(2004, 'Detroit Pistons');
INSERT INTO competition VALUES(2003, 'San Antonio Spurs');
INSERT INTO competition VALUES(2002, 'Los Angeles Lakers');
INSERT INTO competition VALUES(2001, 'Los Angeles Lakers');
INSERT INTO competition VALUES(2000, 'Los Angeles Lakers');
INSERT INTO competition VALUES(1999, 'San Antonio Spurs');
INSERT INTO competition VALUES(1998, 'Chicago Bulls');
INSERT INTO competition VALUES(1997, 'Chicago Bulls');
INSERT INTO competition VALUES(1996, 'Chicago Bulls');
INSERT INTO competition VALUES(1995, 'Houston Rockets');
INSERT INTO competition VALUES(1994, 'Houston Rockets');
INSERT INTO competition VALUES(1993, 'Chicago Bulls');
INSERT INTO competition VALUES(1992, 'Chicago Bulls');
INSERT INTO competition VALUES(1991, 'Chicago Bulls');
INSERT INTO competition VALUES(1990, 'Detroit Pistons');
INSERT INTO competition VALUES(1989, 'Detroit Pistons');
INSERT INTO competition VALUES(1988, 'Los Angeles Lakers');
INSERT INTO competition VALUES(1987, 'Los Angeles Lakers');
INSERT INTO competition VALUES(1986, 'Boston Celtics');
INSERT INTO competition VALUES(1985, 'Los Angeles Lakers');
INSERT INTO competition VALUES(1984, 'Boston Celtics');
INSERT INTO competition VALUES(1983, 'Philadelphia 76ers');
INSERT INTO competition VALUES(1982, 'Los Angeles Lakers');
INSERT INTO competition VALUES(1981, 'Boston Celtics');
INSERT INTO competition VALUES(1980, 'Los Angeles Lakers');
INSERT INTO competition VALUES(1979, 'Seattle SuperSonics');
INSERT INTO competition VALUES(1978, 'Washington Bullets');
INSERT INTO competition VALUES(1977, 'Portland Trail Blazers');
INSERT INTO competition VALUES(1976, 'Boston Celtics');
INSERT INTO competition VALUES(1975, 'Golden State Warriors');
INSERT INTO competition VALUES(1974, 'Boston Celtics');
INSERT INTO competition VALUES(1973, 'New York Knicks');
INSERT INTO competition VALUES(1972, 'Los Angeles Lakers');
INSERT INTO competition VALUES(1971, 'Milwaukee Bucks');
INSERT INTO competition VALUES(1970, 'New York Knicks');
INSERT INTO competition VALUES(1969, 'Boston Celtics');
INSERT INTO competition VALUES(1968, 'Boston Celtics');
INSERT INTO competition VALUES(1967, 'Philadelphia 76ers');
INSERT INTO competition VALUES(1966, 'Boston Celtics');
INSERT INTO competition VALUES(1965, 'Boston Celtics');
INSERT INTO competition VALUES(1964, 'Boston Celtics');
INSERT INTO competition VALUES(1963, 'Boston Celtics');
INSERT INTO competition VALUES(1961, 'Boston Celtics');
INSERT INTO competition VALUES(1960, 'Boston Celtics');
INSERT INTO competition VALUES(1959, 'Boston Celtics');
INSERT INTO competition VALUES(1958, 'St. Louis Hawks');
INSERT INTO competition VALUES(1957, 'Boston Celtics');
INSERT INTO competition VALUES(1956, 'Philadelphia Warriors');
INSERT INTO competition VALUES(1955, 'Syracuse Nationals');
INSERT INTO competition VALUES(1954, 'Minneapolis Lakers');
INSERT INTO competition VALUES(1953, 'Minneapolis Lakers');
INSERT INTO competition VALUES(1952, 'Minneapolis Lakers');
INSERT INTO competition VALUES(1951, 'Rochester Royals');
INSERT INTO competition VALUES(1950, 'Minneapolis Lakers');
INSERT INTO competition VALUES(1949, 'Minneapolis Lakers');
INSERT INTO competition VALUES(1948, 'Baltimore Bullets');
INSERT INTO competition VALUES(1947, 'Philadelphia Warriors');
